# Generated by Django 3.0.3 on 2020-04-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200405_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_create_post', 'User Can Create a new post'),)},
        ),
    ]
