# Generated by Django 3.0.3 on 2020-04-11 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20200411_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='create_uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='creators', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='update_uid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='updaters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
